export const langData = {
  en: {
    login: "Login",
    register: "Register",
    total: "Total",
    logout: "Logout",
    welcome: "Welcome",
    dashboard: 'Dashboard',
    checkout: 'Checkout',
    inventory: 'Inventory',
    reports: 'Reports',
    settings: 'Settings',
    debtTracking: 'Debt Tracking',
    totalSales: "Total Sales",
    todaysSales: "Today Sales",
    transactions: "Transactions",
    products: "Products",
    salesTrend: "Sales Trend",
    summary: "Summary",
    avgTransaction: "Avg Transaction",
    growth: "Growth",
    subtotal: 'Subtotal',
    processPayment: 'Process Payment',
    analytics: "Analytics",
    download: "Download",
    share: "Share",
    sales: "Sales",
    today: "Today",
    week: "Week",
    month: "Month",
    filter: "Filter",
    orders: "Orders",
    productSales: "Product Sales",
    cartEmpty: 'Cart is empty',
    payment: 'Payment Method',
    process: 'Process Payment',
    orderSummary: 'Order Summary',
    gst: 'GST',
    added: 'added to cart',
    removed: 'Item removed',
    empty: 'Cart is empty',
    success: 'Payment Successful',
    card: 'Credit / Debit Card',
    upi: 'UPI Payment',
    cash : 'Cash',
    inventoryManagement: 'Inventory Management',
    addProduct: 'Add Product',
    delete: 'Delete',
    edit: 'Edit',
    save: 'Save',
    cancel: 'Cancel',
    productAdded: 'Product added successfully',
    productDeleted: 'Product deleted',
    fillRequired: 'Please fill all required fields',
    aiInsights: 'AI Insights',
    productName: 'Product Name',
    sku: 'SKU',
    category: 'Category',
    quantity: 'Quantity',
    price: 'Price',
    reorderLevel: 'Reorder Level',
    all: 'All',
    beverages: 'Beverages',
    pulses: 'Pulses',
    essentials: 'Essentials',
    snacks: 'Snacks',
    grains: 'Grains',
    dairy: 'Dairy',
    spices: 'Spices',
    vegetables: 'Vegetables',
    bakery: 'Bakery',
    household: 'Household',
    allS: 'All Stock',
    lowS: 'Low Stock',
    highS: 'In Stock',
    editProduct: "Edit Product",
    actions: "Actions",

    //Reports
    reportsAnalytics: 'Reports & Analytics',
    viewReports: 'View detailed sales and inventory reports',
    exportReport: 'Export Report',
    reportType: 'Report Type',
    salesReport: 'Sales Report',
    inventoryReport: 'Inventory Report',
    productPerformance: 'Product Performance',
    customerReport: 'Customer Report',
    dateRange: 'Date Range',
    thisWeek: 'This Week',
    thisMonth: 'This Month',
    customRange: 'Custom Range',
    date: "Date",
    transaction: "Transaction",
    amount: "Amount",
    status: "Status",
    items: "Items",
    applyFilter: "Apply Filter",
    custom: "Custom Range",
    fromDate: "From Date",
    toDate: "To Date",

    // Settings
    storeSettings: 'Store Settings',
    manageStore: 'Manage your store and system settings',
    editSettings: 'Edit Settings',
    storeInformation: 'Store Information',
    storeName: 'Store Name',
    address: 'Address',
    city: 'City',
    state: 'State',
    zipCode: 'Zip Code',
    country: 'Country',
    email: 'Email',
    website: 'Website',
    currency: 'Currency',
    taxRate: 'Tax Rate',
    businessHours: 'Business Hours',
    license: "License",
    enterKey: "Enter License Key",
    activate: "Activate",
    shopInfo: "Shop Info",
    shopName: "Shop Name",
    appearance: "Appearance",
    language: "Language",
    storeInfo: "Store Information",
    location: "Location",
    financial: "Financial Settings",
    system: "System Info",
  },
  hi: {
    login: "लॉगिन",
    register: "रजिस्टर",
    total: "कुल",
    logout: "लॉगआउट",
    welcome: "स्वागत है",
    dashboard: 'डैशबोर्ड',
    checkout: 'चेकआउट',
    inventory: 'इनवेंटरी',
    reports: 'रिपोर्ट',
    settings: 'सेटिंग्स',
    debtTracking: 'उधार ट्रैकिंग',
    totalSales: "कुल बिक्री",
    todaysSales: "आज की बिक्री",
    transactions: "लेन-देन",
    products: "उत्पाद",
    salesTrend: "बिक्री ट्रेंड",
    summary: "सारांश",
    avgTransaction: "औसत लेन-देन",
    growth: "वृद्धि",
    subtotal: 'उप-योग',
    processPayment: 'भुगतान करें',
    analytics: "विश्लेषण",
    download: "डाउनलोड",
    share: "साझा करें",
    sales: "बिक्री",
    today: "आज",
    week: "इस सप्ताह",
    month: "इस महीने",
    filter: "फ़िल्टर",
    orders: "ऑर्डर",
    productSales: "उत्पाद बिक्री",
    cartEmpty: 'कार्ट खाली है',
    payment: 'भुगतान का तरीका',
    process: 'भुगतान करें',
    orderSummary: 'ऑर्डर सारांश',
    gst: 'जीएसटी',
    added: 'कार्ट में जोड़ा गया',
    removed: 'आइटम हटाया गया',
    empty: 'कार्ट खाली है',
    success: 'भुगतान सफल',
    card: 'क्रेडिट / डेबिट कार्ड',
    upi: 'यूपीआई भुगतान',
    cash : 'नकद',
    inventoryManagement: 'इनवेंटरी प्रबंधन',
    addProduct: 'उत्पाद जोड़ें',
    delete: 'हटाएं',
    edit: 'संपादित करें',
    save: 'सहेजें',
    cancel: 'रद्द करें',
    productAdded: 'उत्पाद सफलतापूर्वक जोड़ा गया',
    productDeleted: 'उत्पाद हटाया गया',
    fillRequired: 'कृपया सभी आवश्यक फ़ील्ड भरें',
    aiInsights: 'एआई अंतर्दृष्टि',
    productName: 'उत्पाद का नाम',
    sku: 'एसकेयू',
    category: 'श्रेणी',
    quantity: 'मात्रा',
    price: 'कीमत',
    reorderLevel: 'पुन: आदेश स्तर',
    all: 'सभी',
    beverages: 'पेय',
    pulses: 'दालें',
    essentials: 'जरूरी सामान',
    snacks: 'नाश्ता',
    grains: 'अनाज',
    dairy: 'डेयरी',
    spices: 'मसाले',
    vegetables: 'सब्जियां',
    bakery: 'बेकरी',
    household: 'घरेलू',
    allS: 'सारा स्टॉक',
    lowS: 'कम स्टॉक',
    highS: 'उपलब्ध',
    editProduct: "प्रोडक्ट संपादित करें",
    actions: "एक्शन",

    // Reports
    reportsAnalytics: 'रिपोर्ट और विश्लेषण',
    viewReports: 'विस्तृत बिक्रय और इनवेंटरी रिपोर्ट देखें',
    exportReport: 'रिपोर्ट निर्यात करें',
    reportType: 'रिपोर्ट प्रकार',
    salesReport: 'बिक्रय रिपोर्ट',
    inventoryReport: 'इनवेंटरी रिपोर्ट',
    productPerformance: 'उत्पाद प्रदर्शन',
    customerReport: 'ग्राहक रिपोर्ट',
    dateRange: 'तारीख श्रृंखला',
    thisWeek: 'इस हफ्ते',
    thisMonth: 'इस महीने',
    customRange: 'कस्टम श्रृंखला',
    date: "तारीख",
    transaction: "लेन-देन",
    amount: "राशि",
    status: "स्थिति",
    items: "आइटम",
    applyFilter: "फ़िल्टर लागू करें",
    custom: "कस्टम सीमा",
    fromDate: "प्रारंभ तिथि",
    toDate: "अंतिम तिथि",

    // Settings
    storeSettings: 'स्टोर सेटिंग्स',
    manageStore: 'अपने स्टोर और सिस्टम सेटिंग्स प्रबंधित करें',
    editSettings: 'सेटिंग्स संपादित करें',
    storeInformation: 'स्टोर जानकारी',
    storeName: 'स्टोर का नाम',
    address: 'पता',
    city: 'शहर',
    state: 'राज्य',
    zipCode: 'ज़िप कोड',
    country: 'देश',
    email: 'ईमेल',
    website: 'वेबसाइट',
    currency: 'मुद्रा',
    taxRate: 'कर दर',
    businessHours: 'व्यावसायिक घंटे',
    license: "लाइसेंस",
    enterKey: "लाइसेंस कुंजी दर्ज करें",
    activate: "सक्रिय करें",
    shopInfo: "दुकान जानकारी",
    shopName: "दुकान का नाम",
    appearance: "रूप",
    language: "भाषा",
    storeInfo: "दुकान की जानकारी",
    location: "स्थान",
    financial: "वित्तीय सेटिंग्स",
    system: "सिस्टम जानकारी",
  },
  mr: {
    login: "लॉगिन",
    register: "नोंदणी",
    total: "एकूण",
    logout: "बाहेर पडा",
    welcome: "स्वागत आहे",
    dashboard: 'डॅशबोर्ड',
    checkout: 'चेकआउट',
    inventory: 'साठा',
    reports: 'अहवाल',
    settings: 'सेटिंग्स',
    debtTracker: 'उधारी ट्रॅकर',
    totalSales: "एकूण विक्री",
    todaysSales: "आजची विक्री",
    transactions: "व्यवहार",
    products: "उत्पादने",
    salesTrend: "विक्री ट्रेंड",
    summary: "सारांश",
    avgTransaction: "सरासरी व्यवहार",
    growth: "वाढ",
    subtotal: 'उप एकूण',
    processPayment: 'भुगतान करें',
    analytics: "विश्लेषण",
    download: "डाउनलोड",
    share: "शेअर करा",
    sales: "विक्री",
    today: "आज",
    week: "या आठवड्यात",
    month: "या महिन्यात",
    filter: "फिल्टर",
    orders: "ऑर्डर्स",
    productSales: "उत्पादन विक्री",
    cartEmpty: 'कार्ट रिकामी आहे',
    payment: 'पेमेंट पद्धत',
    process: 'पेमेंट करा',
    orderSummary: 'ऑर्डर सारांश',
    gst: 'जीएसटी',
    added: 'कार्टमध्ये जोडले',
    removed: 'आयटम काढले',
    empty: 'कार्ट रिकामी आहे',
    success: 'पेमेंट यशस्वी',
    card: 'क्रेडिट / डेबिट कार्ड',
    upi: 'यूपीआई पेमेंट',
    cash : 'रोख',
    inventoryManagement: 'इन्व्हेंटरी व्यवस्थापन',
    addProduct: 'उत्पादन जोडा',
    delete: 'हटवा',
    edit: 'संपादित करा',
    save: 'जतन करा',
    cancel: 'रद्द करा',
    productAdded: 'उत्पादन यशस्वीरित्या जोडले',
    productDeleted: 'उत्पादन हटवले',
    fillRequired: 'कृपया आवश्यक माहिती भरा',
    aiInsights: 'एआय माहिती',
    productName: 'उत्पादनाचे नाव',
    sku: 'एसकेयू',
    category: 'श्रेणी',
    quantity: 'प्रमाण',
    price: 'किंमत',
    reorderLevel: 'रीऑर्डर पातळी',
    all: 'सर्व',
    beverages: 'पेय',
    pulses: 'डाळी',
    essentials: 'आवश्यक वस्तू',
    snacks: 'नाश्ता',
    grains: 'धान्य',
    dairy: 'दुग्धजन्य',
    spices: 'मसाले',
    vegetables: 'भाज्या',
    bakery: 'बेकरी',
    household: 'घरगुती',
    allS: 'सर्व स्टॉक',
    lowS: 'कमी स्टॉक',
    highS: 'उपलब्ध',
    editProduct: "प्रॉडक्ट संपादित करा",
    actions: "अॅक्शन",

        // Reports
      reportsAnalytics: 'अहवाल आणि विश्लेषण',
      viewReports: 'तपशीलवार अहवाल पहा',
      exportReport: 'अहवाल निर्यात करा',
      reportType: 'अहवाल प्रकार',
      salesReport: 'विक्री अहवाल',
      inventoryReport: 'इन्व्हेंटरी अहवाल',
      productPerformance: 'उत्पादन कामगिरी',
      customerReport: 'ग्राहक अहवाल',
      dateRange: 'दिनांक श्रेणी',
      thisWeek: 'या आठवड्यात',
      thisMonth: 'या महिन्यात',
      customRange: 'सानुकूल श्रेणी',
      date: "तारीख",
      transaction: "व्यवहार",
      amount: "रक्कम",
      status: "स्थिती",
      items: "आयटम",
      applyFilter: "फिल्टर लागू करा",
      custom: "सानुकूल श्रेणी",
      fromDate: "सुरुवातीची तारीख",
      toDate: "शेवटची तारीख",

      // Settings
    storeSettings: 'स्टोअर सेटिंग्स',
    manageStore: 'तुमचे स्टोअर व्यवस्थापित करा',
    editSettings: 'सेटिंग्स बदला',
    storeInformation: 'स्टोअर माहिती',
    storeName: 'स्टोअर नाव',
    address: 'पत्ता',
    city: 'शहर',
    state: 'राज्य',
    zipCode: 'पिनकोड',
    country: 'देश',
    email: 'ईमेल',
    website: 'वेबसाइट',
    currency: 'चलन',
    taxRate: 'कर दर',
    businessHours: 'व्यवसाय वेळ',
    license: "परवाना",
    enterKey: "परवाना की टाका",
    activate: "सक्रिय करा",
    shopInfo: "दुकान माहिती",
    shopName: "दुकान नाव",
    appearance: "दिसणे",
    language: "भाषा",
    storeInfo: "दुकान माहिती",
    location: "स्थान",
    financial: "आर्थिक सेटिंग्स",
    system: "सिस्टम माहिती",
  }
}as const;

export type LangKey = keyof typeof langData;